name: CI

on:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64,test]
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT || '1433' }}
      DATABASE: ${{ secrets.DATABASE }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Verify Node.js and npm
        run: |
          Write-Output "Node.js version: $(node --version)"
          Write-Output "npm version: $(npm --version)"
        shell: powershell
        
      - name: list files
        run: Get-ChildItem
        shell: powershell
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
        continue-on-error: true
        
      - name: Verify Bun installation
        run: |
          try {
            # Bunが利用可能かテスト
            $bunVersion = bun --version 2>$null
            if ($LASTEXITCODE -eq 0) {
              Write-Output "✓ Bun is available, version: $bunVersion"
              Write-Output "BUN_AVAILABLE=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            } else {
              throw "Bun command failed"
            }
          } catch {
            Write-Output "⚠️ Bun not available or failed to execute: $_"
            Write-Output "This may be due to permission issues with symlink creation on self-hosted runner"
            Write-Output "Will use npm for all operations"
            Write-Output "BUN_AVAILABLE=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }
        shell: powershell
        
      - name: Clean previous installations (if needed)
        run: |
          if (Test-Path "node_modules") {
            Write-Output "Removing existing node_modules..."
            Remove-Item "node_modules" -Recurse -Force -ErrorAction SilentlyContinue
          }
          if (Test-Path "bun.lockb") {
            Write-Output "Removing existing bun.lockb..."
            Remove-Item "bun.lockb" -Force -ErrorAction SilentlyContinue
          }
          if (Test-Path "package-lock.json") {
            Write-Output "Removing existing package-lock.json..."
            Remove-Item "package-lock.json" -Force -ErrorAction SilentlyContinue
          }
        shell: powershell
        
      - name: Install dependencies
        run: |
          if ($env:BUN_AVAILABLE -eq "true") {
            Write-Output "Installing dependencies with Bun..."
            try {
              bun install
              if ($LASTEXITCODE -ne 0) {
                throw "Bun install failed with exit code $LASTEXITCODE"
              }
              Write-Output "✓ Dependencies installed successfully with Bun"
            } catch {
              Write-Output "❌ Bun install failed: $_"
              Write-Output "Falling back to npm..."
              npm install --verbose
            }
          } else {
            Write-Output "Installing dependencies with npm..."
            Write-Output "Using npm with --legacy-peer-deps to resolve dependency conflicts..."
            npm install --legacy-peer-deps --verbose
          }
        shell: powershell
        
      - name: Verify environment variables
        run: |
          Write-Output "Checking environment variables for Prisma..."
          if ($env:DB_USERNAME) {
            Write-Output "✓ DB_USERNAME is set"
          } else {
            Write-Output "⚠️ DB_USERNAME is not set"
          }
          if ($env:DB_HOST) {
            Write-Output "✓ DB_HOST is set"
          } else {
            Write-Output "⚠️ DB_HOST is not set"
          }
          if ($env:DATABASE) {
            Write-Output "✓ DATABASE is set"
          } else {
            Write-Output "⚠️ DATABASE is not set"
          }
          if ($env:DATABASE_URL) {
            Write-Output "✓ DATABASE_URL is set"
          } else {
            Write-Output "⚠️ DATABASE_URL is not set"
          }
        shell: powershell
        
      - name: generate Prisma client
        run: |
          # DATABASE_URLが設定されていない場合は動的に生成
          if (-not $env:DATABASE_URL -and $env:DB_USERNAME -and $env:DB_PASSWORD -and $env:DB_HOST -and $env:DATABASE) {
            $encodedDatabase = [System.Web.HttpUtility]::UrlEncode($env:DATABASE)
            $dynamicDatabaseUrl = "sqlserver://$($env:DB_USERNAME):$($env:DB_PASSWORD)@$($env:DB_HOST):$($env:DB_PORT)/$encodedDatabase?schema=dbo"
            Write-Output "Generated DATABASE_URL dynamically"
            $env:DATABASE_URL = $dynamicDatabaseUrl
          }
          
          if ($env:BUN_AVAILABLE -eq "true") {
            Write-Output "Generating Prisma client with Bun..."
            try {
              bun run prisma generate
              if ($LASTEXITCODE -ne 0) {
                throw "Bun prisma generate failed with exit code $LASTEXITCODE"
              }
              Write-Output "✓ Prisma client generated successfully with Bun"
            } catch {
              Write-Output "❌ Bun prisma generate failed: $_"
              Write-Output "Falling back to npm..."
              npx prisma generate
            }
          } else {
            Write-Output "Generating Prisma client with npm..."
            npx prisma generate
          }
        shell: powershell
        
      - name: Build project (if available)
        run: |
          $packageJson = Get-Content "package.json" | ConvertFrom-Json
          if ($packageJson.scripts.build) {
            if ($env:BUN_AVAILABLE -eq "true") {
              Write-Output "Building with Bun..."
              try {
                bun run build
                if ($LASTEXITCODE -ne 0) {
                  throw "Bun build failed with exit code $LASTEXITCODE"
                }
                Write-Output "✓ Build completed successfully with Bun"
              } catch {
                Write-Output "❌ Bun build failed: $_"
                Write-Output "Falling back to npm..."
                npm run build
              }
            } else {
              Write-Output "Building with npm..."
              npm run build
            }
          } else {
            Write-Output "No build script found, skipping build"
          }
        shell: powershell
        
      - name: Verify build output
        run: |
          Write-Output "Checking build output..."
          Write-Output "Current directory: $(Get-Location)"
          Write-Output "Contents of current directory:"
          Get-ChildItem
          
          if (Test-Path "dist") {
            Write-Output "Contents of dist directory:"
            Get-ChildItem "dist" -Recurse
          } else {
            Write-Output "❌ dist directory not found"
          }
          
          if (Test-Path "dist/index.js") {
            $indexJsPath = Resolve-Path "dist/index.js"
            Write-Output "✓ dist/index.js found at: $indexJsPath"
            Write-Output "File size: $((Get-Item $indexJsPath).Length) bytes"
          } else {
            Write-Output "❌ dist/index.js not found"
          }
        shell: powershell 

      #pm2がインストールされているか確認
      - name: Verify pm2 installation
        run: |
          try {
            $pm2Version = pm2 --version 2>$null
            if ($LASTEXITCODE -eq 0) {
              Write-Output "✓ pm2 is available, version: $pm2Version"
              Write-Output "Current PM2 processes:"
              pm2 list
            } else {
              throw "pm2 command failed"
            }
          } catch {
            Write-Output "⚠️ pm2 not available or failed to execute: $_"
          }
        shell: powershell
      - name: Start application with pm2
        run: |
          if (Test-Path "dist/index.js") {
            $absoluteIndexPath = Resolve-Path "dist/index.js"
            Write-Output "Deploying application with pm2..."
            Write-Output "Using absolute path: $absoluteIndexPath"
            
            # 既存のプロセスが存在するかチェック（複数の方法で確認）
            $processExists = $false
            try {
              # 方法1: pm2 jlist でチェック
              $processList = pm2 jlist | ConvertFrom-Json
              $existingProcess = $processList | Where-Object { $_.name -eq "bun-test-app" }
              if ($existingProcess) {
                $processExists = $true
                Write-Output "Existing process found via jlist. Current status: $($existingProcess.pm2_env.status)"
              }
            } catch {
              Write-Output "Could not check processes via jlist, trying alternative method..."
              
              # 方法2: pm2 show でチェック
              try {
                pm2 show bun-test-app 2>$null
                if ($LASTEXITCODE -eq 0) {
                  $processExists = $true
                  Write-Output "Existing process found via show command"
                }
              } catch {
                Write-Output "No existing process found via show command"
              }
            }
            
            if ($processExists) {
              Write-Output "Performing zero-downtime reload..."
              pm2 reload bun-test-app
              if ($LASTEXITCODE -eq 0) {
                Write-Output "✓ Application reloaded successfully with pm2 (zero-downtime)"
              } else {
                Write-Output "❌ Reload failed, attempting restart..."
                pm2 restart bun-test-app
                if ($LASTEXITCODE -eq 0) {
                  Write-Output "✓ Application restarted successfully with pm2"
                } else {
                  Write-Output "❌ Restart failed, performing fresh start..."
                  pm2 delete bun-test-app 2>$null
                  pm2 start $absoluteIndexPath --name "bun-test-app"
                }
              }
            } else {
              Write-Output "No existing process found. Starting new process..."
              # -f オプションを追加して強制実行
              pm2 start $absoluteIndexPath --name "bun-test-app" -f
            }
            
            # 最終状態確認
            if ($LASTEXITCODE -eq 0) {
              Write-Output "✓ Application deployment completed successfully"
              pm2 save
              pm2 list
              Write-Output "Recent logs:"
              pm2 logs bun-test-app --lines 20 2>$null
            } else {
              Write-Output "❌ Failed to deploy application with pm2, exit code: $LASTEXITCODE"
              Write-Output "PM2 status:"
              pm2 list
            }
          } else {
            Write-Output "❌ dist/index.js not found, cannot deploy application"
          }
        shell: powershell

