name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v3
      - name: list files
        run: dir
        shell: pwsh
      - name: Install dependencies
        run: bun install
        shell: pwsh
      - name: generate Prisma client
        run: npx prisma generate 
