name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v3
      
      - name: Add Bun to PATH
        run: |
          $bunPath = "C:\Users\Administrator\AppData\Roaming\bun\bin"
          if (Test-Path $bunPath) {
            Write-Output "Adding $bunPath to PATH"
            Write-Output "$bunPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            Write-Output "GITHUB_PATH content:"
            Get-Content $env:GITHUB_PATH
          } else {
            Write-Output "Bun path not found at $bunPath"
            # 他の一般的なBunインストール場所もチェック
            $alternatePaths = @(
              "C:\bun\bin",
              "C:\Program Files\bun\bin",
              "${env:USERPROFILE}\.bun\bin"
            )
            foreach ($path in $alternatePaths) {
              if (Test-Path $path) {
                Write-Output "Adding $path to PATH"
                Write-Output "$path" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
                break
              }
            }
          }
        shell: powershell
          
      - name: Check Bun version (with full path)
        run: |
          $bunExe = "C:\Users\Administrator\AppData\Roaming\bun\bin\bun.exe"
          if (Test-Path $bunExe) {
            & $bunExe --version
          } else {
            Write-Output "Bun executable not found at $bunExe"
            exit 1
          }
        shell: powershell
        
      - name: list files
        run: Get-ChildItem
        shell: powershell
        
      - name: Install dependencies
        run: |
          $bunExe = "C:\Users\Administrator\AppData\Roaming\bun\bin\bun.exe"
          & $bunExe install
        shell: powershell
        
      - name: generate Prisma client
        run: |
          $bunExe = "C:\Users\Administrator\AppData\Roaming\bun\bin\bun.exe"
          & $bunExe run prisma generate
        shell: powershell
        
      - name: Build project
        run: |
          $bunExe = "C:\Users\Administrator\AppData\Roaming\bun\bin\bun.exe"
          & $bunExe run build
        shell: powershell 
