name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v3
          
      - name: Check Bun version
        run: bun --version
        shell: powershell
        
      - name: list files
        run: Get-ChildItem
        shell: powershell
        
      - name: Install dependencies
        run: bun install
        shell: powershell
        
      - name: generate Prisma client
        run: bun run prisma generate
        shell: powershell
        
      - name: Build project
        run: bun run build
        shell: powershell 
